import { createFileRoute } from "@tanstack/react-router";
import { SITE_URL } from "@/lib/seo";

export const Route = createFileRoute("/robots.txt")({
  server: {
    handlers: {
      GET: () => {
        const origin = SITE_URL;
        // Host directive theo chuẩn không có scheme.
        const host = origin.replace(/^https?:\/\//, "");
        const body = [
          "# robots.txt — Lcucumber",
          "# Content-Signal for Search Engines & AI Assistants",
          "Content-Signal: search=yes,ai-train=no,use=immediate",
          "",
          "# Search Engine Crawlers",
          "User-agent: Googlebot",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /admin-applications",
          "Disallow: /apply",
          "Disallow: /login",
          "Disallow: /api/",
          "",
          "User-agent: Googlebot-Image",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /api/",
          "",
          "User-agent: Bingbot",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /admin-applications",
          "Disallow: /apply",
          "Disallow: /login",
          "Disallow: /api/",
          "",
          "User-agent: Applebot",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /api/",
          "",
          "User-agent: DuckDuckBot",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /api/",
          "",
          "# Disallow AI Training Scrapers & Bulk Model Data Harvesters",
          "User-agent: GPTBot",
          "Disallow: /",
          "",
          "User-agent: CCBot",
          "Disallow: /",
          "",
          "User-agent: Bytespider",
          "Disallow: /",
          "",
          "User-agent: ClaudeBot",
          "Disallow: /",
          "",
          "User-agent: anthropic-ai",
          "Disallow: /",
          "",
          "User-agent: Google-Extended",
          "Disallow: /",
          "",
          "User-agent: FacebookBot",
          "Disallow: /",
          "",
          "User-agent: PerplexityBot",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /admin-applications",
          "Disallow: /apply",
          "Disallow: /login",
          "Disallow: /api/",
          "",
          "# Default rule for all other crawlers",
          "User-agent: *",
          "Allow: /",
          "Disallow: /admin",
          "Disallow: /admin-applications",
          "Disallow: /apply",
          "Disallow: /login",
          "Disallow: /api/",
          "",
          `Host: ${host}`,
          `Sitemap: ${origin}/sitemap.xml`,
          `Sitemap: ${origin}/sitemap-index.xml`,
          "",
        ].join("\n");
        return new Response(body, {
          headers: {
            "content-type": "text/plain; charset=utf-8",
            "cache-control": "public, max-age=3600",
          },
        });
      },
    },
  },
});