/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminApplicationsRouteImport } from './routes/admin-applications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruyenSlugRouteImport } from './routes/truyen.$slug'
import { Route as TheLoaiSlugRouteImport } from './routes/the-loai.$slug'
import { Route as SitemapTheLoaiSlugDotxmlRouteImport } from './routes/sitemap-the-loai.$slug[.]xml'
import { Route as ApiDriveFileRouteImport } from './routes/api/drive-file'
import { Route as TruyenSlugChuongChar123numChar125RouteImport } from './routes/truyen.$slug.chuong-{$num}'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin-applications',
  path: '/admin-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugRoute = TruyenSlugRouteImport.update({
  id: '/truyen/$slug',
  path: '/truyen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TheLoaiSlugRoute = TheLoaiSlugRouteImport.update({
  id: '/the-loai/$slug',
  path: '/the-loai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapTheLoaiSlugDotxmlRoute =
  SitemapTheLoaiSlugDotxmlRouteImport.update({
    id: '/sitemap-the-loai/$slug.xml',
    path: '/sitemap-the-loai/$slug.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDriveFileRoute = ApiDriveFileRouteImport.update({
  id: '/api/drive-file',
  path: '/api/drive-file',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugChuongChar123numChar125Route =
  TruyenSlugChuongChar123numChar125RouteImport.update({
    id: '/chuong-{$num}',
    path: '/chuong-{$num}',
    getParentRoute: () => TruyenSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/sitemap-the-loai/$slug.xml': typeof SitemapTheLoaiSlugDotxmlRoute
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRouteWithChildren
  '/truyen/$slug/chuong-{$num}': typeof TruyenSlugChuongChar123numChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/sitemap-the-loai/$slug.xml': typeof SitemapTheLoaiSlugDotxmlRoute
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRouteWithChildren
  '/truyen/$slug/chuong-{$num}': typeof TruyenSlugChuongChar123numChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/sitemap-the-loai/$slug.xml': typeof SitemapTheLoaiSlugDotxmlRoute
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRouteWithChildren
  '/truyen/$slug/chuong-{$num}': typeof TruyenSlugChuongChar123numChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/featured'
    | '/latest'
    | '/login'
    | '/robots.txt'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/api/drive-file'
    | '/sitemap-the-loai/$slug.xml'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug/chuong-{$num}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/featured'
    | '/latest'
    | '/login'
    | '/robots.txt'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/api/drive-file'
    | '/sitemap-the-loai/$slug.xml'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug/chuong-{$num}'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/featured'
    | '/latest'
    | '/login'
    | '/robots.txt'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/api/drive-file'
    | '/sitemap-the-loai/$slug.xml'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug/chuong-{$num}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  FeaturedRoute: typeof FeaturedRoute
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiDriveFileRoute: typeof ApiDriveFileRoute
  SitemapTheLoaiSlugDotxmlRoute: typeof SitemapTheLoaiSlugDotxmlRoute
  TheLoaiSlugRoute: typeof TheLoaiSlugRoute
  TruyenSlugRoute: typeof TruyenSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-applications': {
      id: '/admin-applications'
      path: '/admin-applications'
      fullPath: '/admin-applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug': {
      id: '/truyen/$slug'
      path: '/truyen/$slug'
      fullPath: '/truyen/$slug'
      preLoaderRoute: typeof TruyenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-loai/$slug': {
      id: '/the-loai/$slug'
      path: '/the-loai/$slug'
      fullPath: '/the-loai/$slug'
      preLoaderRoute: typeof TheLoaiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-the-loai/$slug.xml': {
      id: '/sitemap-the-loai/$slug.xml'
      path: '/sitemap-the-loai/$slug.xml'
      fullPath: '/sitemap-the-loai/$slug.xml'
      preLoaderRoute: typeof SitemapTheLoaiSlugDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-file': {
      id: '/api/drive-file'
      path: '/api/drive-file'
      fullPath: '/api/drive-file'
      preLoaderRoute: typeof ApiDriveFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug/chuong-{$num}': {
      id: '/truyen/$slug/chuong-{$num}'
      path: '/chuong-{$num}'
      fullPath: '/truyen/$slug/chuong-{$num}'
      preLoaderRoute: typeof TruyenSlugChuongChar123numChar125RouteImport
      parentRoute: typeof TruyenSlugRoute
    }
  }
}

interface TruyenSlugRouteChildren {
  TruyenSlugChuongChar123numChar125Route: typeof TruyenSlugChuongChar123numChar125Route
}

const TruyenSlugRouteChildren: TruyenSlugRouteChildren = {
  TruyenSlugChuongChar123numChar125Route:
    TruyenSlugChuongChar123numChar125Route,
}

const TruyenSlugRouteWithChildren = TruyenSlugRoute._addFileChildren(
  TruyenSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  ApplyRoute: ApplyRoute,
  FeaturedRoute: FeaturedRoute,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiDriveFileRoute: ApiDriveFileRoute,
  SitemapTheLoaiSlugDotxmlRoute: SitemapTheLoaiSlugDotxmlRoute,
  TheLoaiSlugRoute: TheLoaiSlugRoute,
  TruyenSlugRoute: TruyenSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
